require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :macos, '10.14'

target 'ghost_writer_rn-macOS' do
  config = use_native_modules!
  use_react_native!(
    :path => '../node_modules/react-native-macos',
    
    # To use Hermes, install the `hermes-engine-darwin` npm package, e.g.:
    #   $ yarn add 'hermes-engine-darwin@~0.5.3'
    #
    # Then enable this option:
    #   :hermes_enabled => true
  )

  # Pods specifically for macOS target
end

target 'MyShareExt-macOS' do
  use_react_native!(
    :path => '../node_modules/react-native-macos',
  )
  pod 'ReactNativeShareExtension', :path => '../node_modules/react-native-share-extension'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name.equal? "MyShareExt-macOS"
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
        build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    else
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
